# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{socky}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernard Potocki"]
  s.date = %q{2010-10-28}
  s.description = %q{Transitional package for socky-server gem}
  s.email = %q{bernard.potocki@imanel.org}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
     "lib/socky.rb",
     "socky.gemspec"
  ]
  s.homepage = %q{http://github.com/socky/socky-server-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Transitional package for socky-server gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<socky-server>, ["~> 0.4.0"])
    else
      s.add_dependency(%q<socky-server>, ["~> 0.4.0"])
    end
  else
    s.add_dependency(%q<socky-server>, ["~> 0.4.0"])
  end
end

